---
- name: Install docker
  hosts: all
  become: yes
  
  tasks:

    - name: Install docker, docker-compose, prometheus-node-exporter
      apt: 
         update_cache: true
         pkg: ["docker", "docker-compose", "prometheus-node-exporter"]

    - name: Starting docker containers 
      community.docker.docker_compose:
        project_src: /opt/docker
        build: yes
