# Pull prometheus on virtual container from Docker Hub
FROM prom/prometheus
# The ADD instruction copies new files, directories or remote file URLs from <src> and adds them to the filesystem of the image
COPY prometheus.yml /etc/prometheus/
