version: '2'

networks:
  localnet:
    driver: bridge

services:

  prometheus:
    build:
      context: /opt/docker/prom
      dockerfile: Dockerfile
    container_name: prometheus
    hostname: prometheus
    networks:
      - localnet
  grafana:
    build:
      context: /opt/docker/grafana
      dockerfile: Dockerfile
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - localnet
